Traceback (most recent call last):
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Initiate a CATHY model
# ------------------------
path2prj = '.'  # add your local path here
simu = cathy_tools.CATHY(dirName=path2prj, prj_name="LaCecilia_2022_HP")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 4[0m
[1;32m      1[0m [38;5;66;03m# Initiate a CATHY model[39;00m
[1;32m      2[0m [38;5;66;03m# ------------------------[39;00m
[1;32m      3[0m path2prj [38;5;241m=[39m [38;5;124m'[39m[38;5;124m.[39m[38;5;124m'[39m  [38;5;66;03m# add your local path here[39;00m
[0;32m----> 4[0m simu [38;5;241m=[39m [43mcathy_tools[49m[38;5;241;43m.[39;49m[43mCATHY[49m[43m([49m[43mdirName[49m[38;5;241;43m=[39;49m[43mpath2prj[49m[43m,[49m[43m [49m[43mprj_name[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mLaCecilia_2022_HP[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/pyCATHY-0.1.1-py3.10.egg/pyCATHY/cathy_tools.py:292[0m, in [0;36mCATHY.__init__[0;34m(self, dirName, prj_name, notebook, version, verbose, **kwargs)[0m
[1;32m    289[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;28mself[39m[38;5;241m.[39mworkdir, [38;5;28mself[39m[38;5;241m.[39mproject_name, [38;5;124m"[39m[38;5;124moutput[39m[38;5;124m"[39m)):
[1;32m    290[0m         [38;5;28mself[39m[38;5;241m.[39mcreate_output(output_dirname[38;5;241m=[39m[38;5;124m"[39m[38;5;124moutput[39m[38;5;124m"[39m)
[0;32m--> 292[0m         [43mshutil[49m[38;5;241;43m.[39;49m[43mrmtree[49m[43m([49m
[1;32m    293[0m [43m            [49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mworkdir[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mproject_name[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mtmp_src[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m    294[0m [43m        [49m[43m)[49m
[1;32m    295[0m         os[38;5;241m.[39mremove(os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;28mself[39m[38;5;241m.[39mworkdir, [38;5;28mself[39m[38;5;241m.[39mproject_name, [38;5;124m"[39m[38;5;124mreadme.txt[39m[38;5;124m"[39m))
[1;32m    297[0m [38;5;66;03m# clear output files if required[39;00m
[1;32m    298[0m [38;5;66;03m# ---------------------------------------------------------------------[39;00m

File [0;32m~/miniconda3/envs/pyCATHY_doc/lib/python3.10/shutil.py:715[0m, in [0;36mrmtree[0;34m(path, ignore_errors, onerror)[0m
[1;32m    713[0m     orig_st [38;5;241m=[39m os[38;5;241m.[39mlstat(path)
[1;32m    714[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[0;32m--> 715[0m     [43monerror[49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mlstat[49m[43m,[49m[43m [49m[43mpath[49m[43m,[49m[43m [49m[43msys[49m[38;5;241;43m.[39;49m[43mexc_info[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    716[0m     [38;5;28;01mreturn[39;00m
[1;32m    717[0m [38;5;28;01mtry[39;00m:

File [0;32m~/miniconda3/envs/pyCATHY_doc/lib/python3.10/shutil.py:713[0m, in [0;36mrmtree[0;34m(path, ignore_errors, onerror)[0m
[1;32m    710[0m [38;5;66;03m# Note: To guard against symlink races, we use the standard[39;00m
[1;32m    711[0m [38;5;66;03m# lstat()/open()/fstat() trick.[39;00m
[1;32m    712[0m [38;5;28;01mtry[39;00m:
[0;32m--> 713[0m     orig_st [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mlstat[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m    714[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    715[0m     onerror(os[38;5;241m.[39mlstat, path, sys[38;5;241m.[39mexc_info())

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/z0272571a@CAMPUS.CSIC.ES/Nextcloud/BenCSIC/Codes/BenjMy/pycathy_wrapper/doc/jupyter_execute/jupyter_execute/jupyter_execute/content/FromLiterature/./LaCecilia_2022_HP/tmp_src'

